### ISSUE TITLE
midterm-jpark.py is ready

### ISSUE THREAD

**Issue by rleonard-matc** [madisoncollege-it-programs/python-scripting-rleonard-matc#10]

**Comment by cethenmc** [comment]
Thanks for putting in a very solid effort on this part of the midterm.  I like how clean the code is.  The first part I analyze is program execution.  I figured out in a couple of seconds that the counter was not showing the number of retry attempts (1 pt).  Then I jump into the code   Lines 30 - 38 should fall into one if statement without hardcoding.  The evaluation can be done given the input and against the dictionary in a couple of lines (2 pts).  Score 30/33.
