### ISSUE TITLE
midterm-if.py is ready

### ISSUE THREAD

**Issue by rleonard-matc** [madisoncollege-it-programs/python-scripting-rleonard-matc#11]
It is not finished I honestly only figured out the true goal of the script an hour before I turned it in but I had to go to work, so I put in what I had done before . Even though I had figured out the true purpose, I still don't think I could have figured it out however, I am not making an excuse.

**Comment by cethenmc** [comment]
All concepts you used were concepts learned in class, which was nice to see.  However, you missed the mark a bit in this section printing the length of each line you must have found manually.  Do to the concepts you demonstrated being concepts we learned, you will receive a score of 16/33.
