### ISSUE TITLE
f2c.py and tempconversion.py for functions lab are both up in Week9

### ISSUE THREAD

**Issue by rleonard-matc** [madisoncollege-it-programs/python-scripting-rleonard-matc#12]

**Comment by cethenmc** [comment]
Well done.  8 of 8.

I will also add that if the tempconversion.py was intended to be run through the "main()" function:  "Script 2 - Temp Conversion (**Main**)."  You may consider modifying your tempconversion.py script or creating another (tempconversion2.py) where it will use __name__ to ensure the main() function runs.  Your main function can be the code you made in tempconversion.py.
