### ISSUE TITLE
Initial commit of Argparse lab under arguments.py in Weak11

### ISSUE THREAD

**Issue by rleonard-matc** [madisoncollege-it-programs/python-scripting-rleonard-matc#14]

**Comment by cethenmc** [comment]
Nice job overall.  A couple of things were missed, so I am setting your score at 6 of 8.  Please resubmit for full credit soon or reply to this Issue Ticket if you just want to keep the score.

1. The help screen differs from the picture in the Lab.
    a. the -i line.  Your long flag is not labeled the same (I can ignore the misspelling in the metavar).
    b. the -s line.  Missing long flag.
    c. the -l line.  This should have no long flag, as you do not see double hyphens in that line.
2. The instructions were clear to print four of the arguments, and you seemed to leave that out.
3. You made the float required, but it should have been the integer.

**Comment by rleonard-matc** [comment]
Second push of Arguments.py is up and should be fixed.

**Comment by cethenmc** [comment]
1.a. in the note above is still an issue.  Here is the diff of your help results versus the key (I let everyone have a break on the the hyphen in 'setfalse', but if you plan to correct 1a, you could fix this one, too.

If you are content with your new 7.5 out of 8 on this lab, then please reply to this ticket saying so, or submit again to gain the last half point.

Thanks.

~Chris

Chris

**Comment by rleonard-matc** [comment]
I should have fixed the half point issue.

**Comment by cethenmc** [comment]
Looks good.  Now 8 out of 8 for Week 11.
