### ISSUE TITLE
Initial commit of networking lab in Week12, all of the codes in there.

### ISSUE THREAD

**Issue by rleonard-matc** [madisoncollege-it-programs/python-scripting-rleonard-matc#15]

**Comment by cethenmc** [comment]
Hi Rhett.  The chat portion of the lab looks great.  The filetransfer I cannot grade.  Permissions were not set right from the command line, and even when I did set them to executable, the client and server script both throw errors.  Recording 4 of 8 for now.  Please resubmit, or let me know if you prefer keeping the 4.  Hopefully, you can either get help during a lab, or maybe you forgot to push your latest version.  Please let me know either way.

![image](https://user-images.githubusercontent.com/112707666/204965902-2f552da6-bc66-442a-a8f0-479e8de9dd98.png)

**Comment by rleonard-matc** [comment]
I have repushed the filetransfer client and server and the file.txt and they should be completed.

**Comment by cethenmc** [comment]
Fantastic!  8 out of 8.
