### ISSUE TITLE
Initial commit of lab 13 interacting with web site, in Week13

### ISSUE THREAD

**Issue by rleonard-matc** [madisoncollege-it-programs/python-scripting-rleonard-matc#16]
The two actual scripts are named inspect-web.py and copy-web.py. The others are a script to make a server to test the copied web site and the actual html of the copied web site.

**Comment by cethenmc** [comment]
These look great!  

The directions were unclear in when it was asking to get every link; it also wanted the href.  With the rules being unclear, I accept the link name you provide.  I would also take just the links.  In an ideal world, I would see both.  If you would like to print both, simply change your last print statement to:

print(f"{link.text}:  {link.get('href')}")

or something equivalent.  You don't have to resubmit.  **Your score is 8 out of 8.**  This is for your own knowledge in case you are asked to do something similar in the future.
