### ISSUE TITLE
My final exam is posted and up in github

### ISSUE THREAD

**Issue by rleonard-matc** [madisoncollege-it-programs/python-scripting-rleonard-matc#18]
It does not work, I couldn't figure it out and ran out of time, am hoping for partial credit for what I did do right, hopefully I did some right.

**Comment by cethenmc** [comment]
Would you benefit from more time the remainder of today?  Or do you feel you got it as far as you could get it?  Let me know by 2 PM if you think the remainder of the day would help you.  I will hold yours until after 2 PM to grade.

Chris

[signature_146958654]
Chris Ethen | Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>


From: rleonard-matc ***@***.***>
Sent: Thursday, December 15, 2022 9:17 PM
To: madisoncollege-it-programs/python-scripting-rleonard-matc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [madisoncollege-it-programs/python-scripting-rleonard-matc] My final exam is posted and up in github (Issue #18)


It does not work, I couldn't figure it out and ran out of time, am hoping for partial credit for what I did do right, hopefully I did some right.

-

**Comment by cethenmc** [comment]
![image](https://user-images.githubusercontent.com/112707666/208173080-893d988f-03b4-4a6f-9735-7f027d9f6afe.png)
