### ISSUE TITLE
Lab Data Types uploaded in the Week4 file under name of sequences.py

### ISSUE THREAD

**Issue by rleonard-matc** [madisoncollege-it-programs/python-scripting-rleonard-matc#4]

**Comment by cethenmc** [comment]
Rhett - Great work.  however, I will caution you.  Although it did not make a difference for this exercise, please do not use the same variable for the item/element/character in the for loop as the sequence variable name.

for varString in varString:
    print (varString)

instead, please get in the habit of making the element a different name from the sequence, like the following:

for varStringChar in varString:
    print(varStringChar)

Full credit on this one, but please follow this recommendation.

Chris
