### ISSUE TITLE
Initial commit of File Data Interactions: named files.py found in Week5

### ISSUE THREAD

**Issue by rleonard-matc** [madisoncollege-it-programs/python-scripting-rleonard-matc#5]

**Comment by cethenmc** [comment]
# 1 and # 2 are fine.  However, # 3 needs work.  Book me on Monday, or stop in Tuesday.  You can decide how important it is to your success on the midterm to determine if it is a rush or not.  If you want to take another jab at it before meeting, then consider this information.

The key is to use readline() and ensure that with each line you read, you append it to a variable. This allows you to satisfy the requirement to save the entire content to a variable one line at a time.

For now, I will record a 6 of 8 in the grade book.  Please reply to this ticket either when new code is pushed to fix the issue, or to tell me to just keep the 6 of 8.

**Comment by cethenmc** [comment]
Thanks for meeting today.  Please reply to this GitHub Issue Ticket when you have pushed your changes to GitHub.  Thanks!

**Comment by rleonard-matc** [comment]
Final commit is up for this.

**Comment by cethenmc** [comment]
Thanks for the stick-with-it-ness!  Persistence pays off.  Full credit!
